#!/bin/bash

# Display listening TCP ports with associated PID and program name
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tuln | grep '^tcp\|tcp6' | awk '{print $1, $4, $5, $6}' | sed 's/:::/[::]/g' | while read line; do
    proto=$(echo $line | awk '{print $1}')
    local_addr=$(echo $line | awk '{print $2}')
    foreign_addr=$(echo $line | awk '{print $3}')
    state=$(echo $line | awk '{print $4}')
    pid=$(netstat -tuln | grep -w "$proto" | grep -w "$local_addr" | grep -w "$foreign_addr" | awk '{print $7}' | cut -d'/' -f1)
    program_name=$(ps -p $pid -o comm=)
    echo "$proto $local_addr $foreign_addr $state $pid/$program_name"
done

# Display listening UDP ports with associated PID and program name
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -uln | grep '^udp\|udp6' | awk '{print $1, $4, $5, $6}' | sed 's/:::/[::]/g' | while read line; do
    proto=$(echo $line | awk '{print $1}')
    local_addr=$(echo $line | awk '{print $2}')
    foreign_addr=$(echo $line | awk '{print $3}')
    state=$(echo $line | awk '{print $4}')
    pid=$(netstat -uln | grep -w "$proto" | grep -w "$local_addr" | grep -w "$foreign_addr" | awk '{print $7}' | cut -d'/' -f1)
    program_name=$(ps -p $pid -o comm=)
    echo "$proto $local_addr $foreign_addr $state $pid/$program_name"
done

